server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///home/andrew/IdeaProjects/spring cloud demo/config-service/src/main/resources/config
